language: python

# TODO : fix this
#env:
#    #global:
#      #- FLAKE8_FLAGS: "--exclude=old,extras,tests --ignore E402"

python:
  - 3.4
  - 3.5

env:
  - NUMPY=1.10
  - NUMPY=1.11

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ~/mc
  - export PATH=~/mc/bin:$PATH
  - conda update conda --yes
  - export CONDARC=ci/condarc

install:
  - conda create -n testenv pip nose python=$TRAVIS_PYTHON_VERSION numpy=$NUMPY coverage cython flake8 scipy
  - source activate testenv
  - python setup.py install build_ext -i
  - pip install codecov

script:
  - coverage run run_tests.py
  - flake8 --exclude=old,extras,tests --ignore E402,E226,W503 $TRAVIS_BUILD_DIR/ScatterSim 

after_success:
#  - codecov

